#!/usr/bin/env bash
# nginx server configuration to listen on port 80

# nginx config  to listen on port 80 for all IPV4 Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# nginx start
service nginx restart
